[tools]
ruby = "3"
usage = "latest"
go = "1"
fzf = "latest"
"go:github.com/charmbracelet/gum" = "latest"
tf-summarize = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:neovim/neovim" = "latest"
"asdf:mise-plugins/mise-eza" = "latest"
"asdf:mise-plugins/mise-tmux" = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"
lazygit = "latest"
lazydocker = "latest"
fd = "latest"
jq = "latest"
node = "latest"
rg = "latest"
air = "latest"
golangci-lint = "latest"
bat = "latest"
zoxide = "latest"
"go:github.com/ankitpokhrel/jira-cli/cmd/jira" = "latest"
postgres = "15"
rust = "latest"
rust-analyzer = "latest"
lua-language-server = "latest"
terraform = "latest"
yazi = "latest"
k9s = "latest"
yarn = "latest"
yq = "latest"
"cargo:presenterm" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
