[tools]
ruby = "3"
usage = "latest"
go = "1.25.0"
fzf = "latest"
"go:github.com/charmbracelet/gum" = "latest"
tf-summarize = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:neovim/neovim" = "latest"
"asdf:mise-plugins/mise-eza" = "latest"
"asdf:mise-plugins/mise-tmux" = "latest"
lazygit = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"dailypay:dp" = "1.8.0"
"dailypay:default-pndelim-investigation" = "0.7.0"
"dailypay:default-pndelim-awsso" = "1.1.5"
"dailypay:default-pndelim-release" = "1.1.0"
"dailypay:default-pndelim-mesh" = "1.0.1"
"dailypay:default-pndelim-git" = "0.3.0"
"dailypay:default-pndelim-grpc-stub" = "1.3.1"
"dailypay:default-pndelim-hydra" = "0.1.0"
"dailypay:default-pndelim-playground" = "1.0.0"
"dailypay:default-pndelim-pproxy" = "1.0.0"
"dailypay:default-pndelim-reload" = "1.0.0"
"dailypay:default-pndelim-sql-seed-generator" = "0.4.2"
"dailypay:default-pndelim-ssr-gen" = "0.1.0"
"dailypay:default-pndelim-templ" = "1.0.0"
"dailypay:default-pndelim-terraform" = "1.1.1"
fd = "latest"
jq = "latest"
node = "latest"
rg = "latest"
air = "latest"
golangci-lint = "latest"
bat = "latest"
zoxide = "latest"
"go:github.com/ankitpokhrel/jira-cli/cmd/jira" = "latest"
postgres = "15"
rust = "latest"
rust-analyzer = "latest"
lua-language-server = "latest"
terraform = "latest"
yazi = "latest"
k9s = "latest"
yarn = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
