[tools]
ruby = "3"
usage = "latest"
go = "latest"
fzf = "latest"
"aqua:yorukot/superfile" = "latest"
"go:github.com/charmbracelet/gum" = "latest"
tf-summarize = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
